### PR TITLE
modernization to chuck 1.4.0

### PR DESCRIPTION
**Pull request by dbadb**
two primary issues: 

- Random is now "taken" so I renamed the class to LRandom
- Chubgraph is now Chugraph, change eliminated deprecation warnings.

### CODE REVIEW

**Comment by heuermh** [comment]
Thank you for the pull request, @dbadb!  I hadn't heard about the `Chubgraph` change in ChucK, seems fine.

The issue with `Random` was discussed in https://github.com/heuermh/lick/issues/11, I'd rather try pushing upstream for them to change, as the Random chugin is kind of the non-standard thing.  I will do a pull request there with a name change and see what happens.

**Comment by dbadb** [comment]
Hi Michael, no problem and I do see your point on the Random global keyword.
This world without namespacing is a bit of a challenge.
Let me know how you'd like to proceed with this request:  1. cancel or 2. undo the LRandom change.

**Comment by heuermh** [comment]
I'd say leave this pull request as-is for a little while.  I started thinking about some other changes I had in the back of my mind and am creating issues for those.  Will see what the chugin folks think about the proposed name change.

**Comment by dbadb** [comment]
oops - our messages passed each other in the ether.
I'll be happy to re-integrate the LRandom change at any time (presumably after you hear back from the chugin folks). I suspect that you're right though, the Random chugin appears vestigial and probably shouldn't get in the way of your ownership of this name.

**Comment by dbadb** [comment]
oh - and while i have your attention, on windows 10 your tests.ck caused chuck 1.4... to crash.  I identified a fix (an uninitialized variable in chuck) and have a pull-request pending.  Should you wish to workaround this issue in your test suite, I recall that it was associated with the assertinRange function and its use of multiple Object-to-string  (iirc).

**Comment by heuermh** [comment]
You do have my attention!  Please feel free to file issues for bugs & feature requests; I'm doing the same 😄

**Review by heuermh — APPROVED** [review]

**Comment by heuermh** [comment]
Hmm, this may be a problem
```
$ chuck import.ck
...
[chuck](VM): sporking incoming shred: 293 (Module8.ck)...
[Hyper.ck]:line(37): undefined type 'Chugraph'...
[Hyper.ck]:line(37): undefined super class 'Chugraph' in definition of class 'Hyper'
[SampleHold.ck]:line(24): undefined type 'Chugraph'...
[SampleHold.ck]:line(24): undefined super class 'Chugraph' in definition of class 'SampleHold'
...
```

I see commits https://github.com/ccrma/chuck/commit/c1e26a18cbcf17a0ad06bdb680200da7f385d644 and https://github.com/ccrma/chuck/commit/54f1bcd49edad88affd649712af097d38b4f1a62 but I can't find a version 1.4.0.2 release version to download anywhere, nor is there a release tag on https://github.com/ccrma/chuck/releases.

**Comment by dbadb** [comment]
aha - so I guess I'm on the bleeding edge.  I've been building chuck from the source.
I see that you poked at the chuck mailing list. It will be interesting to learn where
the 1.4.0.2 release stands.

**Comment by heuermh** [comment]
No problem!  I've reverted the commit for now, and will reapply this pull request once a 1.4.0.2 release is ready.

**Pull request merged**
